# Cosmos-Predict2-2B, Adaptive Projected Guidance.
pipeline: pipelines.cosmos2.apg
generation_params:
  height: 1024
  width: 1024
  num_inference_steps: 35
  guidance_scale: 7.0
  method: apg
  apg_eta: 0.0
  apg_step_radius: 15.0
  apg_momentum: -0.5
