source /home/aaturevich/.venv/bin/activate
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/cfg.py --outdir /home/aaturevich/geneval/outputs/cfg_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/cfg_05022026 --outfile /home/aaturevich/geneval/outputs/cfg_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/no_cfg.py --outdir /home/aaturevich/geneval/outputs/no_cfg_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/no_cfg_05022026 --outfile /home/aaturevich/geneval/outputs/no_cfg_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/pag.py --outdir /home/aaturevich/geneval/outputs/pag_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/pag_05022026 --outfile /home/aaturevich/geneval/outputs/pag_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/sag_0.3_cfg6.0.py --outdir /home/aaturevich/geneval/outputs/sag_0.3_cfg6.0_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/sag_0.3_cfg6.0_05022026 --outfile /home/aaturevich/geneval/outputs/sag_0.3_cfg6.0_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/sag_0.4_cfg5.0.py --outdir /home/aaturevich/geneval/outputs/sag_0.4_cfg5.0_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/sag_0.4_cfg5.0_05022026 --outfile /home/aaturevich/geneval/outputs/sag_0.4_cfg5.0_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/seg_sigma10_cfg3.py --outdir /home/aaturevich/geneval/outputs/seg_sigma10_cfg3_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/seg_sigma10_cfg3_05022026 --outfile /home/aaturevich/geneval/outputs/seg_sigma10_cfg3_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/seg_sigmainf_cfg3.py --outdir /home/aaturevich/geneval/outputs/seg_sigmainf_cfg3_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/seg_sigmainf_cfg3_05022026 --outfile /home/aaturevich/geneval/outputs/seg_sigmainf_cfg3_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
python /home/aaturevich/geneval/generation/diffusers_generate.py /home/aaturevich/geneval/prompts/prompts_05022026/evaluation_metadata.jsonl --config /home/aaturevich/geneval/model_configs/slg.py --outdir /home/aaturevich/geneval/outputs/slg_05022026
python /home/aaturevich/geneval/evaluation/evaluate_images.py /home/aaturevich/geneval/outputs/slg_05022026 --outfile /home/aaturevich/geneval/outputs/slg_05022026/results.jsonl --model-path /home/aaturevich/geneval/models --model-config /home/aaturevich/geneval/mmdetection/configs/mask2former/mask2former_swin-s-p4-w7-224_8xb2-lsj-50e_coco.py
